flannel_semaphore: "/home/{{ ssh_user }}/applied_flanel_pod_network"
host_security_groups:
  - group: "k8s-master{{ suffix }}"
    port: 6443
    remote_ip_prefix: "{{ ssh_remote_cidr }}"
  - group: "k8s-master{{ suffix }}"
    port: 2379
    port_end: 2380
    remote_group: "k8s-master{{ suffix }}"
  - group: "k8s-master{{ suffix }}"
    port: 10251
    remote_group: "k8s-master{{ suffix }}"
  - group: "k8s-master{{ suffix }}"
    port: 10252
    remote_group: "k8s-master{{ suffix }}"
  - group: "k8s-master{{ suffix }}"
    port: 10250
    remote_group: "k8s-master{{ suffix }}" 
  - group: "k8s-master{{ suffix }}"
    port: 10255
    remote_group: "k8s-master{{ suffix }}" 
