host_security_groups:
  - group: "k8s-worker{{ suffix }}"
    port: 30000
    port_end: 32767
    remote_ip_prefix: "0.0.0.0/0"
  - group: "k8s-worker{{ suffix }}"
    port: 10250
    remote_group: "k8s-master{{ suffix }}" 
  - group: "k8s-worker{{ suffix }}"
    port: 10255
    remote_group: "k8s-master{{ suffix }}" 
