- name: Create cloud hosts file
  hosts: localhost
  tasks:
    - debug:
        var: prefix | mandatory

    - name: Create host file for kubernetes cluster
      template:
        src: templates/hosts.j2
        dest: "{{ lookup('env', 'PWD') }}/cloud-hosts"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}" 
        mode: '0644'
