- name: Set up course materials
  hosts: localhost
  tags: materials
  tasks:
    - name: Clone kubernetes lessons
      git:
        version: master
        repo: https://github.com/heytrav/k8s-ansible.git
        dest: "{{ lookup('env', 'HOME') }}/k8s-ansible"

    - name: Check out prometheus repository
      git:
        version: master
        repo: https://github.com/coreos/prometheus-operator 
        dest: "{{ lookup('env', 'HOME') }}/prometheus-operator"
        force: true

    - name: Check out voting app repository
      git:
        version: master
        repo: https://github.com/docker/example-voting-app.git
        dest: "{{ lookup('env', 'HOME') }}/example-voting-app"
        force: true

- name: Install nodejs
  hosts: localhost
  become: true
  roles:
    - role: trainingpc-nodejs

- name: Set up reveal presentation
  hosts: localhost
  tags: setup
  tasks:

    - name: Set up reveal presentation
      command: npm install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/kubernetes-microservices-workshop/slides"
        creates: node_modules

