- name: Set up course materials
  hosts: localhost
  tags: materials
  tasks:
    - name: Clone kubernetes lessons
      git:
        version: master
        repo: https://github.com/heytrav/k8s-ansible.git
        dest: "{{ lookup('env', 'HOME') }}/k8s-ansible"

- name: Install nodejs
  hosts: localhost
  become: true
  roles:
    - role: trainingpc-nodejs

- name: Set up reveal presentation
  hosts: localhost
  tags: setup
  tasks:

    - name: Set up reveal presentation
      command: npm install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/kubernetes-microservices-workshop/slides"
        creates: node_modules

